#! /usr/bin/env python

import os
import sys
from subprocess import check_call
join = os.path.join

def maybe(f):
    def tryer(*args, **kwargs):
        try:
            f(*args, **kwargs)
        except Exception as e:
            print('    %s' % e)
    return tryer


# dest dir
d = os.environ['HOME']

@maybe
def symlink(x, y, makedir=False):
    # source dir
    s = os.path.realpath(os.path.dirname(__file__))

    src = join(s, x)
    dest = join(d, y)
    if makedir:
        os.makedirs(os.path.dirname(dest), exist_ok=True)
    print(src + '......' + dest)
    if os.path.exists(src):
        os.symlink(src, dest)
    else:
        print("    DOESN'T EXIST: %s" % src)


def install_vim():
    # new version:
    print("Please install packages:  the_silver_searcher neovim ")
    check_call('git clone --depth=1 https://github.com/amix/vimrc.git ~/.vim_runtime', shell=True)
    check_call('curl -fLo ~/.vim_runtime/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', shell=True)
    print("For Coc autocomplete to work, please install:  yarn nodejs")
    print("The Coc autocomplete vim library is installed from vim plug line in the vimrc.")
    print("The vimrc is located at ~/.vim_runtime/my_configs.vim and accessable in vim via <leader>e  (the leader is comma)")
    symlink('vimrc', join(d, '.vim_runtime/my_configs.vim'))
    symlink('vimrc', join(d, '.config/nvim/init.vim'))
    check_call('sh ~/.vim_runtime/install_awesome_vimrc.sh', shell=True)
    check_call('mkdir ~/.vim_runtime/spell', shell=True)
    # symlink("en.utf-8.add", "~/.vim_runtime/spell/en.utf-8.add")
    print("After installing dependencies, start vim and run: ")
    print(":PlugInstall")
    print(":CocInstall")

def update_vim():
    print("Running updates, but but may not give error messages.")
    check_call('nvim +PlugUpgrade +qa', shell=True)
    check_call('nvim +PlugUpdate +qa', shell=True)
    check_call('nvim +CocUpdateSync +qa', shell=True)
    print("... I just ran these in vim commandline, one at a time:")
    print("  :PlugUpgrade :PlugUpdate :CocUpdate")

#########################################
#########################################


if __name__ == '__main__':
    import argparse as ap
    p = ap.ArgumentParser()
    p.add_argument('--vim', action='store_true')
    p.add_argument('--update-vim', action='store_true')
    p.add_argument('--docker', action='store_true')
    p.add_argument('--symlinks', action='store_true')
    p.add_argument('--bootstrap_init_host', action='store_true')
    NS = p.parse_args()

    if NS.bootstrap_init_host:
        check_call(
            (
             'mkdir ~/s ; '
             'git clone git@github.com:adgaudio/dot_files.git ~/s/dot_files;'
             ),
            shell=True)
        print("bootstrap_init_host called.  All other args disabled while this one is enabled")
        print("To install again, try: %s" % ' cd ~/s/dot_files ; ./install -h ')
        sys.exit(0)

    if NS.symlinks:
        symlink("ackrc", ".ackrc")
        symlink("bash_aliases", ".bash_aliases")
        symlink("bash_functions", ".bash_functions")
        symlink("bash_extras", ".bash_extras")
        symlink("ctags", ".ctags")
        symlink("flake8", ".config/flake8", makedir=True)
        symlink("foot.ini", ".config/foot/foot.ini", makedir=True)
        symlink("profile", ".profile")
        # symlink("sway_config", ".config/sway/config", makedir=True)
        symlink("hyprland.conf", ".config/hypr/hyprland.conf", makedir=True)
        symlink("hypridle.conf", ".config/hypr/hypridle.conf", makedir=True)
        symlink("waybar_config", ".config/waybar/config", makedir=True)
        symlink("waybar_style.css", ".config/waybar/style.css", makedir=True)
        symlink("zshrc", ".zshrc")
        symlink("zsh_tab_completion", ".zsh_tab_completion")
        symlink("zshrc.zni", ".zshrc.zni")
        symlink("z.sh", ".z.sh")

        symlink("gitconfig", ".gitconfig")
        symlink("inputrc", ".inputrc")
        symlink("python/pythonrc.py", ".pythonrc.py")
        symlink("Rprofile", ".Rprofile")

        _ipy_dir = join(d, ".ipython/profile_np/startup")
        if not os.path.exists(_ipy_dir):
            os.makedirs(_ipy_dir)
        symlink("ipython/profile_np/startup/10-imports.ipy",
                join(_ipy_dir, "10-imports.ipy"))

        symlink("tmux/tmux.conf", ".tmux.conf")
        symlink("tmux/tmux_osx.conf", ".tmux_osx.conf")
        if 'linux' in sys.platform.lower():
            symlink("Xmodmap", ".Xmodmap")

        _bin = join(d, "bin")
        if not os.path.exists(_bin):
            os.makedirs(_bin)
        symlink("bin/vnc.sh", join(_bin, "vnc.sh"))
        symlink("bin/backup", join(_bin, "backup"))
        symlink("bin/init_revealjs_presentation.sh", join(_bin, "init_revealjs_presentation.sh"))

        _unison = join(d, ".unison")
        os.makedirs(_unison, exist_ok=True)
        symlink("unison/default.prf", join(_unison, "default.prf"))

        symlink('python.snippets', '.config/coc/ultisnips/python.snippets', makedir=True)
        symlink('coc-settings.json', '.config/nvim/coc-settings.json')

    if NS.vim:
        install_vim()
    # Install realiaser (for cmd prompt)
    # os.system('gem install realiaser')  # gem update realiaser
    if NS.update_vim:
        update_vim()

    if NS.docker:
        if os.environ.get('BOX_NAME'):
            print(
                "NOT Building docker devbox image because it looks"
                " like I'm inside a docker container already")
        else:
            files = sorted(os.listdir(join(
                os.path.dirname(__file__), 'dockerfiles')))
            # build devbox and printer and ...
            for fn in files:
                if not fn.endswith('.Dockerfile'):
                    continue
                tag = fn.split('.', 1)[0]
                cmd = (
                    "cd dockerfiles ; docker build -t adgaudio/{0} "\
                    "-f {1} .").format(tag, fn)
                print(cmd)
                check_call(cmd, shell=True)
