#!/bin/bash
set -e
cwd="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Install dependencies?
#sudo apt-get install pep8

echo "installing janus"
curl -Lo- http://bit.ly/janus-bootstrap | bash

echo "sym linking vimrc.before and vimrc.after to $HOME"
[ -e ~/.vimrc.before ] && mv ~/.vimrc.before ~/.vimrc.before.old
ln -s $cwd/vimrc.before ~/.vimrc.before
[ -e ~/.vimrc.after ] && mv ~/.vimrc.after ~/.vimrc.after.old
ln -s $cwd/vimrc.after ~/.vimrc.after

echo "Adding extra vim plugins in $HOME/.janus"
[ -e ~/.janus ] || mkdir ~/.janus
(
cd ~/.janus 
git init
$cwd/add_and_update_janus_plugins
)

echo "enjoy!"
